### PR TITLE
Allow specifying an offset on onewire sensor

### PR DESCRIPTION
**Pull request by carlallen**
closes https://github.com/Manuel83/craftbeerpi3/issues/33

alternatively as a plugin: https://github.com/carlallen/cbpi_BiasedOneWireSensor

### CODE REVIEW

**Comment by IndyJoeA** [comment]
I wonder if you could move the offset up into the root Sensor class, so that any sensor will have an offset?  I know it would be more work, possibly modifying the database, but then any sensor would have an offset available, like future Type-K or RTD sensors, or the iSpindel/Tilt sensors, or the flow meter, etc...

**Comment by carlallen** [comment]
should just be able to add it to SensorBase which wouldn't require a database change

**Comment by carlallen** [comment]
Other sensor types can easily copy the same code for their offsets

**Comment by IndyJoeA** [comment]
You are right, the dummy sensor doesn't need an offset, but I would think any other sensor would benefit from having it as a basic form of calibration, and doing it now while 3.0 is in beta would be a good time so that future sensor plugins would automatically have that feature.  I'm fine with it either way, just thought I'd share my opinion.

**Pull request merged**
