### PR TITLE
Replace int with float in get_sensor_value()

### PR DESCRIPTION
**Pull request by IndyJoeA**
I've noticed that sensor values are being handled as integers by this function, which was causing poor performance of the PIDArduino logic and another logic plugin I am testing.  I have changed the type to float, and now logic controllers can receive more accurate temperature values.

### CODE REVIEW

**Comment by swimIan** [comment]
What "poor performance" were you noticing?

**Comment by IndyJoeA** [comment]
I was seeing large overshoots (5 degrees), and my autotune plugin (work in progress) was also failing because it couldn't converge.  Changing sensors from int to float solved both problems.

**Comment by swimIan** [comment]
I tried it to make the suggested changes but I apparently don't have permission to change core.py. How did you change the permissions.

**Comment by IndyJoeA** [comment]
Type sudo nano ~/craftbeerpi3/modules/core/core.py

**Comment by swimIan** [comment]
Does this still need to be done for your autotune plugin to work correctly?

**Comment by IndyJoeA** [comment]
Well not really, auto tune will still run fine but it might not be as accurate since all the temps it's seeing are rounded to 0 digits because they're integers.  You might not notice any problems on your system, but because mine is so slow to respond to temp changes it was giving me problems initially.  Not sure why Manuel chose to make temps read as ints, he probably had a good reason, or perhaps it was for debugging reasons and can be changed back now.

**Pull request merged**
